name: build

on: [push, pull_request]

jobs:
  linux:
    strategy:
      matrix:
        r: [latest]
        # r: [3.5, latest, devel]
        python: [3.7]
        # python: [2.7, 3.4, 3.5, 3.6, 3.7]
    runs-on: ubuntu-latest
    container: rocker/tidyverse:${{ matrix.r }}
    steps:
      - uses: actions/checkout@v1
      - name: Install apt-get dependencies
        run: |
          apt-get update
          apt-get install git ssh curl bzip2 libffi6 libffi-dev -y
      - name: Setup Miniconda
        run: |
          curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
          bash /tmp/miniconda.sh -b -f -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin/:$PATH"
          if [ "${{ matrix.python }}" == "3.4" ]; then
            conda create -y -n myenv python=${{ matrix.python }} -c conda-forge
          else
            conda create -y -n myenv python=${{ matrix.python }}
          fi
          echo "::add-path::$HOME/miniconda/bin"
      - name: Install reticulate
        run: Rscript -e "install.packages('reticulate', repo = 'https://cloud.r-project.org')"
      - name: Install and running tests
        shell: bash  # to allow `source`
        run: |
          source activate myenv
          python -m pip install -e .[test]
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`R RHOME`/lib"
          pytest -s --cov=rchitect
          python -m pip install codecov
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  macos:
    strategy:
      matrix:
        r: [latest]
        # r: [3.5, latest, devel]
        python: [3.7]
        # python: [2.7, 3.4, 3.5, 3.6, 3.7]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Miniconda
        run: |
          curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o /tmp/miniconda.sh
          bash /tmp/miniconda.sh -b -f -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          if [ "${{ matrix.python }}" == "3.4" ]; then
            conda create -y -n myenv python=${{ matrix.python }} -c conda-forge
          else
            conda create -y -n myenv python=${{ matrix.python }}
          fi
          echo "::add-path::$HOME/miniconda/bin"
      - name: Install R
        run: |
          if [ "${{ matrix.r }}" = "devel" ]; then
            R_FILE=$(curl -sL http://mac.r-project.org/ | sed -nE 's|.*href="?(.*/R-[^/]*\.pkg)"?>.*|\1|p' | tail -n1)
            URL="http://mac.r-project.org/$R_FILE"
          else
            R_FILE=$(curl -sL https://cran.r-project.org/bin/macosx/el-capitan/base/ | grep -o 'R-${{ matrix.r }}[0-9\.]*.pkg' | tail -n1)
            URL="https://cran.r-project.org/bin/macosx/el-capitan/base/$R_FILE"
          fi
          echo downloading "$URL"
          curl -L "$URL" -o R.pkg
          sudo installer -pkg R.pkg -target /
      - name: Install reticulate
        run: Rscript -e "install.packages('reticulate', repo = 'https://cloud.r-project.org')"
      - name: Install and running tests
        run: |
          source activate myenv
          python -m pip install -e .[test]
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`R RHOME`/lib"
          pytest -s --cov=rchitect
          python -m pip install codecov
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  windows:
    strategy:
      matrix:
        r: [latest]
        # r: [3.5, latest, devel]
        python: [3.7]
        # python: [2.7, 3.4, 3.5, 3.6, 3.7]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Miniconda
        run: |
          $env:PATH = "$env:CONDA;$env:CONDA\Scripts;$env:PATH"
          If ('${{ matrix.r }}' -eq '3.4') {
            conda create -y -n myenv python=${{ matrix.python }} -c conda-forge
          } Else {
            conda create -y -n myenv python=${{ matrix.python }}
          }
          conda init powershell
      - name: Install R
        run: |
          If ('${{ matrix.r }}' -eq 'latest') {
            (new-object net.webclient).DownloadString("http://cran.rstudio.com/bin/windows/base/") -match 'href="(R-[0-9.]*[a-zA-Z]*-win.exe)"';
            (new-object net.webclient).DownloadFile($("http://cran.rstudio.com/bin/windows/base/"+$matches[1]),"C:\R-binary.exe")
          } ElseIf ('${{ matrix.r }}' -eq 'devel') {
            (new-object net.webclient).DownloadFile("https://cran.r-project.org/bin/windows/base/R-devel-win.exe","C:\R-binary.exe")
          } Else {
            (new-object net.webclient).DownloadString("http://cran.rstudio.com/bin/windows/base/old/") -match 'R (${{ matrix.r }}[\\.0-9]*)</a>'
            (new-object net.webclient).DownloadFile($("https://cran.r-project.org/bin/windows/base/old/"+$matches[1]+"/R-"+$matches[1]+"-win.exe"),"C:\R-binary.exe")
          }
          Start-Process -FilePath "C:\R-binary.exe" -Wait -ArgumentList "/VERYSILENT /DIR=C:\R"
          echo "::add-path::C:\R\bin\x64"
      - name: Install reticulate
        run: |
          $ErrorActionPreference = "Continue"
          Rscript -e "install.packages('reticulate', repo = 'https://cloud.r-project.org', type = 'win.binary')"
      - name: Install
        run: |
          conda activate myenv
          python -m pip install -e .[test]
      - name: Running tests
        run: |
          conda activate myenv
          pytest -s --cov=rchitect
          python -m pip install codecov
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  build_wheels:
    needs: [linux, macos, windows]
    name: Build wheel on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        name: Install Python
        with:
          python-version: '3.7'
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.3.0
      - name: Install Visual C++ for Python 2.7
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install vcpython27 -f -y
      - name: Build wheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v1
        with:
          name: wheels
          path: ./wheelhouse

  twine:
    name: Upload tarball and wheels
    if: startsWith(github.ref, 'refs/tags/')
    needs: build_wheels
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{secrets.TWINE_USERNAME}}
      TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        name: Install Python
        with:
          python-version: '3.7'
      - run: python -m pip install twine
      - run: |
          python setup.py sdist
          python -m twine upload dist/*
      - uses: actions/download-artifact@v1
        with:
          name: wheels
          path: ./wheelhouse
      - run: python -m twine upload ./wheelhouse/*.whl
